server:
  port: 80
spring:
  application:
    name: atguigu-crowd-zuul
  redis:
    host: 192.168.19.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    crowd-portal:
      service-id: atguigu-crowd-auth
      path: /**
    crowd-project:
      service-id: atguigu-crowd-project
      path: /project/**
    crowd-order:
      service-id: atguigu-crowd-order
      path: /order/**
ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000