server:
  port: 5000
spring:
  application:
    name: atguigu-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.19.128
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI4G2Mth3HAt49tnTWACt2
    access-key-secret: 7PGyKIUZSVcCUogiWuhYz5mVjmrNKf
    bucket-domain: https://space0531.oss-cn-shenzhen.aliyuncs.com
    bucket-name: space0531
    end-point: http://oss-cn-shenzhen.aliyuncs.com